### ISSUE TITLE
Error `Futures timed out` during setup

### ISSUE THREAD

**Issue by guori12321** [ISG-ICS/cloudberry#474]
Hi, I'm trying to setup the Twitter map demo locally following the [official guide](http://cloudberry.ics.uci.edu/quick-start/), however I got the following error. Any idea on how to fix this? Did I miss anything when setup things?

```
ProvisionException: Unable to provision, see the following errors:

1) Error injecting constructor, java.util.concurrent.TimeoutException: Futures timed out after [1 minute]
  at controllers.TwitterMapApplication.<init>(TwitterMapApplication.scala:22)
  at controllers.TwitterMapApplication.class(TwitterMapApplication.scala:22)
  while locating controllers.TwitterMapApplication
    for parameter 1 at router.Routes.<init>(Routes.scala:31)
  while locating router.Routes
  while locating play.api.inject.RoutesProvider
  while locating play.api.routing.Router
    for parameter 0 at play.api.http.JavaCompatibleHttpRequestHandler.<init>(HttpRequestHandler.scala:200)
  while locating play.api.http.JavaCompatibleHttpRequestHandler
  while locating play.api.http.HttpRequestHandler
    for parameter 4 at play.api.DefaultApplication.<init>(Application.scala:220)
  at play.api.DefaultApplication.class(Application.scala:220)
  while locating play.api.DefaultApplication
  while locating play.api.Application

1 error
```

The java version I'm using is
```
ray@dev:~/cloudberry/cloudberry$ java -version
openjdk version "1.8.0_151"
OpenJDK Runtime Environment (build 1.8.0_151-8u151-b12-0ubuntu0.16.04.2-b12)
OpenJDK 64-Bit Server VM (build 25.151-b12, mixed mode)
```

In fact, I'm trying to install the Twitter map demo on an Azure Ubuntu machine at http://52.230.69.192:9001/  .
 And before I attempted to install Cloudberry on Azure,  I failed to do so on my local Macbook with the error (it is very similar to the above one except the exception name).
```
1) Error injecting constructor, org.asynchttpclient.exception.RemotelyClosedException: Remotely closed
  at controllers.TwitterMapApplication.<init>(TwitterMapApplication.scala:22)
  at controllers.TwitterMapApplication.class(TwitterMapApplication.scala:22)
```

Thanks for your time and help!

**Comment by baiqiushi** [comment]
@guori12321  Hi, thanks for contacting us! Here's our Gitter online discussion Link : https://gitter.im/ISG-ICS/cloudberry , We could discuss details there.

**Comment by chenlica** [comment]
@ruig2 is the bug still valid?  Solution?

**Comment by baiqiushi** [comment]
Low priority.
