### ISSUE TITLE
OutOfMemoryError in Cloudberry

### ISSUE THREAD

**Issue by baiqiushi** [ISG-ICS/cloudberry#531]
```
2018-06-27 16:54:14,131 [DEBUG] from application in ForkJoinPool-1-worker-31 - Query:
select coll_count(
(select value c from (select value t
from twitter.ds_tweet_56ab24c15b72a457069c5ea42fcfc640 t) as c)
) as `count`;
2018-06-27 18:36:47,655 [ERROR] from akka.actor.ActorSystemImpl in application-akka.actor.default-dispatcher-16639 - Uncaught fatal error from thread [application-akka.actor.default-dispatcher-16634] shutting down ActorSystem [application]
java.lang.OutOfMemoryError: Java heap space
2018-06-27 18:40:57,177 [ERROR] from akka.actor.ActorSystemImpl in application-akka.actor.default-dispatcher-16639 - Uncaught fatal error from thread [application-akka.actor.default-dispatcher-16636] shutting down ActorSystem [application]
java.lang.OutOfMemoryError: Java heap space
	at scala.collection.mutable.ArrayBuffer.sizeHint(ArrayBuffer.scala:69)
	at scala.collection.mutable.Builder$class.sizeHint(Builder.scala:69)
	at scala.collection.mutable.ArrayBuffer.sizeHint(ArrayBuffer.scala:48)
	at scala.collection.TraversableLike$class.builder$1(TraversableLike.scala:230)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:233)
	at scala.collection.AbstractTraversable.map(Traversable.scala:104)
	at play.api.libs.json.Json$.obj(Json.scala:152)
	at play.api.libs.json.JsPath$.step$1(JsPath.scala:137)
	at play.api.libs.json.JsPath$.play$api$libs$json$JsPath$$buildSubPath$1(JsPath.scala:147)
	at play.api.libs.json.JsPath$$anonfun$createObj$1.apply(JsPath.scala:152)
	at play.api.libs.json.JsPath$$anonfun$createObj$1.apply(JsPath.scala:150)
	at scala.collection.IndexedSeqOptimized$class.foldl(IndexedSeqOptimized.scala:57)
	at scala.collection.IndexedSeqOptimized$class.foldLeft(IndexedSeqOptimized.scala:66)
	at scala.collection.mutable.WrappedArray.foldLeft(WrappedArray.scala:35)
	at play.api.libs.json.JsPath$.createObj(JsPath.scala:150)
	at play.api.libs.json.PathWrites$$anonfun$at$2.apply(JsConstraints.scala:161)
	at play.api.libs.json.PathWrites$$anonfun$at$2.apply(JsConstraints.scala:161)
	at play.api.libs.json.OWrites$$anon$2.writes(Writes.scala:79)
	at play.api.libs.json.OFormat$$anon$2.writes(Format.scala:48)
	at play.api.libs.json.OWrites$$anon$5$$anonfun$apply$1.apply(Writes.scala:68)
	at play.api.libs.json.OWrites$$anon$5$$anonfun$apply$1.apply(Writes.scala:68)
	at play.api.libs.json.OWrites$$anon$2.writes(Writes.scala:79)
	at play.api.libs.json.OFormat$$anon$2.writes(Format.scala:48)
	at play.api.libs.json.OWrites$$anon$5$$anonfun$apply$1.apply(Writes.scala:68)
	at play.api.libs.json.OWrites$$anon$5$$anonfun$apply$1.apply(Writes.scala:68)
	at play.api.libs.json.OWrites$$anon$2.writes(Writes.scala:79)
	at play.api.libs.json.OFormat$$anon$2.writes(Format.scala:48)
	at play.api.libs.json.OWrites$$anon$5$$anonfun$apply$1.apply(Writes.scala:68)
	at play.api.libs.json.OWrites$$anon$5$$anonfun$apply$1.apply(Writes.scala:68)
	at play.api.libs.json.OWrites$$anon$2.writes(Writes.scala:79)
	at play.api.libs.json.OFormat$$anon$2.writes(Format.scala:48)
	at play.api.libs.json.OWrites$$anon$5$$anonfun$apply$1.apply(Writes.scala:68)
2018-06-27 18:48:16,661 [ERROR] from akka.actor.ActorSystemImpl in application-akka.actor.default-dispatcher-16639 - Uncaught fatal error from thread [application-akka.actor.default-dispatcher-16638] shutting down ActorSystem [application]
java.lang.OutOfMemoryError: Java heap space
2018-06-27 18:48:16,662 [DEBUG] from akka.actor.LocalActorRefProvider$Guardian in application-akka.actor.default-dispatcher-16639 - now supervising Actor[akka://application/user/$Um#1697338798]
2018-06-27 18:48:21,908 [DEBUG] from akka.stream.impl.StreamSupervisor in application-akka.actor.default-dispatcher-16639 - now supervising Actor[akka://application/user/StreamSupervisor-0/flow-2170-0-actorRefSource#163778485]
2018-06-27 18:54:41,180 [DEBUG] from akka.stream.impl.ActorRefSourceActor in application-akka.actor.default-dispatcher-16665 - started (akka.stream.impl.ActorRefSourceActor@1e36628a)
2018-06-27 19:10:16,362 [ERROR] from akka.actor.ActorSystemImpl in application-akka.actor.default-dispatcher-16665 - Uncaught fatal error from thread [application-akka.actor.default-dispatcher-16644] shutting down ActorSystem [application]
java.lang.OutOfMemoryError: Java heap space
```

**Comment by chenlica** [comment]
@baiqiushi status?

**Comment by baiqiushi** [comment]
Low priority.
